[parity]
mode = "dark"
chain = "dev"
base_path = "/Users/troy/Library/Application Support/io.parity.ethereum/dev"
identity = "dev"

# [account]
# unlock = ["0x00942329AB865c8D88Ed261ea1bEc576e08eF26e"]
# password = ["passwords"]

[network]
reserved_only = true
reserved_peers = "./reserved_peers"

[rpc]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]

[websockets]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]

[ipc]
apis = ["web3", "eth", "net", "parity", "parity_accounts", "personal", "traces", "rpc", "secretstore"]
